default_settings: null
behaviors:
  SnakeRobot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 128
    summary_freq: 1000
    threaded: false
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: ./SnakeRobot/test1_16.exe
  env_args: null
  base_port: 5005
  num_envs: 4
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 400
  height: 400
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters:
  stage_number:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 164
          value: 1.0
      name: stage1
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 165
          value: 2.0
      name: stage2
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 166
          value: 3.0
      name: stage3
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1.1
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 167
          value: 4.0
      name: stage4
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 1.125
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 167
          value: 5.0
      name: stage5
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 2.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 167
          value: 6.0
      name: ForStage5EarlyStopping
      completion_criteria:
        behavior: SnakeRobot
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 4.8
        require_reset: false
checkpoint_settings:
  run_id: test16
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: true